

services:
  postgres:
    image: 'postgres:15'
    container_name: java_tutotial_postgres
    restart: always
    environment:
      - 'POSTGRES_DB=java_tutotial'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    networks:
      - app-network

  java_tutotial_redis:
    image: redis:8.0
    container_name: java_tutotial_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "10002:8001"
    depends_on:
      - java_tutotial_redis
    environment:
      - REDIS_HOST=java_tutotial_redis
      - REDIS_PORT=6379
    networks:
      - app-network
    

  app:
    build: .
    depends_on:
      - java_tutotial_redis
      - postgres
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true 
      - SPRING_DOCKER_COMPOSE_ENABLED=false

      - SPRING_CACHE_TYPE=redis
      - SPRING_DATA_REDIS_HOST=java_tutotial_redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge